spring:
  kafka:
    bootstrap-servers: 172.30.1.109:9092
    consumer:
      group-id: group-id-oing
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#---
#spring:
#  config:
#    activate:
#      on-profile: file
#server:
#  port: 1234
#camel:
#  springboot:
#    routes-include-pattern: file:yaml/file/*.yaml
#---
#spring:
#  config:
#    activate:
#      on-profile: http
#server:
#  port: 1235
#camel:
#  springboot:
#    routes-include-pattern: file:yaml/http/*.yaml
#---
#spring:
#  config:
#    activate:
#      on-profile: rest
#server:
#  port: 1236
#camel:
#  springboot:
#    routes-include-pattern: file:yaml/rest/*.yaml
#---
#spring:
#  config:
#    activate:
#      on-profile: srv
#server:
#  port: 9999
#camel:
#  springboot:
#    routes-include-pattern: file:yaml/srv/*.yaml